### ISSUE TITLE
User Experience and Performance

### ISSUE THREAD

**Issue by Fabyao** [microsoft/linux-vm-tools#28]
@cwilhit I am not sure if this is the right place to report user experience and performance issues. I thought you might want some feed back:

**My Host Machine:**
Surface Book 2 16GB RAM, Core I7, 512GB HD running Windows 10 Build 1803

**My Virtual Machine:**
4 CPUs, 8GB RAM, 256 HD running Ubuntu 18.04 (final release) in enhanced session full screen.

**My experience:**
The user experience is poor. Sluggish UI as if the screen is being redrawn frame by frame when minimising/maximising/switching between apps. Scrolling moves the page too far up or down with no options to adjust mouse settings through XRDP. Typing experience feels odd with a slight delay.
As a web developer this is unusable. VMWARE does a better job at virtualising Ubuntu (with minor issues).

This is a shame, it would have made the perfect development environments for my projects.
 Iam now contemplating dual boot however due to some hardware compatibility issues, listed here: https://github.com/jakeday/linux-surface/issues I will have some limitations... 
@cwilhit It will be interesting to know if Microsoft would ever release a Linux kernel for the Surface line?

**Comment by cwilhit** [comment]
Is this for 16.04 or 18.04? What you are describing is abnormal and not an expected experience--something must not be working somewhere along the line. To be sure, can you verify for me that when you connect to the VM, you are greeted with the XRDP login screen with the blue background and you successfully connect via that?

We will have the pre-configured ubuntu image in our quick create gallery shortly. It may be best for you to wait until then and use that instead.

**Comment by Fabyao** [comment]
@cwilhit Thanks for your reply. I am definitely using XRDP with Ubuntu 18.04. Its good to know that what I am experiencing is abnormal. 

I am looking forward to the pre-configured Ubuntu image. Is there a web site I should monitor to find out when its released?

**Comment by cwilhit** [comment]
We'll make a blog post at https://blogs.technet.microsoft.com/virtualization/.

Or if you're on twitter and that's easier, you can [follow me](https://twitter.com/CraigWilhite) and I'll tweet out when it gets updated.

**Comment by grbinho** [comment]
Hi guys, I can confirm the same experience that @Fabyao is reporting.

I'm running a T460p with Quad-Core core i7 with 32GB and pretty much the same VM as @Fabyao.

Will try again when pre-configured image is released.

**Comment by spacecat** [comment]
My Host Machine:
Surface Book 2 16GB RAM, Core I7, 512GB HD running Windows 10 Build 1803

Same perf issues as above.

Also when running ubuntu 16.04 in full screen everything is super tiny.

Actually it does not matter which resolution I choose, it is still super tiny. Can hardly read any text unless I get superclose to the screen.

**Comment by jterry75** [comment]
@grbinho - Do you happen to have the WQHD IPS monitor on that laptop? If so my guess is this is a high DPI bug in common between all three cases.

**Comment by grbinho** [comment]
@jterry75 Yes. It's a WQHD display.

**Comment by jterry75** [comment]
Thanks for the response. I will track down a High DPI display and try this out. Its almost certainly the reason for the low performance you all are seeing.

**Comment by Luminger** [comment]
I do experience the same sluggishness and slow redraw issues described as well. Looking at my system spec it seems to be related to HiDPI indeed, here's what I'm running:

Dell XPS 15 9560 (3840x2160 builtin display, i7-7700HQ, 32GB Ram)
Windows 10 Build 1803
Fresh Ubuntu 18.04 on Hyper-V, treated with the scripts from this repo

Install went smooth and I'm greeted with the separate RDP login screen as expected, so I would think it's installed properly.

**Comment by pdeva** [comment]
i am having a similar issue.
I have a 4k display with nvidia 1080 card.
I even enabled the remote fx 3d driver, but the ui seems to be painting frame by frame.
very poor experience

**Comment by Loyen** [comment]
Same issue here.

**Host machine:**
i7-5820k
16GB ram
Geforce 980

**Virtual machine:**
Ubuntu 18.04
8Gb ram
RemoteFX with 1GB and max resolution of 4k (3820x2160)

Pretty smooth ride up to this point I got to say, its the sluggish UI performance that keeps me away for now. 

@cwilhit Gonna keep an eye out for that image for sure!

**Comment by robcresswell** [comment]
Same here:

**Host** Windows 10 on latest non-insider, 16GB RAM, 1440p screen, i7 7700k
**VM** Ubuntu 18.04, 8GB RAM, RemoteFX with 1GB and max res of 2560x1600.

I had the usual resolution prompts and blue screen etc. All worked well but the end result is laggy :)

**Comment by codekoenig** [comment]
I have the same issues and want to share my observations here too. My setup:

- Ubuntu 18.04 on Hyper-V, executed the 18.04 `install.sh` script from this repo
- Windows 10 1804, powershell script to enable HvSocket executed

It seems everything works fine, I get the XRDP login screen, can use the VM in full screen, use copy & paste and so on. The process was very straightforward, I tried it couple of weeks ago and it was much less refined then. That's aweseome!

But I suffer the same performance problems others have pointed out here:

- Overall very sluggish, laggy UI/UX ... any effects in Ubuntu seem to run with 5 fps
- I also suffer from the mentioned keyboard input lag, making it very hard to to anything productive in the VM
- CPU utilization is very high as soon as i start doing anything, if only moving my mouse pointer around (for examle hovering over icons on the dock).

The high CPU utilization is mostly consumed by the `gnome-shell` process and it's anywhere between 70 and 90 % on 4 cores while moving the mouse - until i stop moving the pointer. 

I added the RemoteFX virtual graphics adapter to the Hyper-V VM, but I don't know if this can even be utilized over XRDP as I suspected that UI rendering seems to be the bottleneck here. But it didn't help and I think Ubuntu simply cannot make use of it.

As there was a discussion about High DPI displays causing this issue - I only have a 1920x1200 screen here on my PC. And I have a 1080p screen on my Dell XPS 15 - on both the performance is not good enough so it can be used. Just fyi, the XPS 15 does have i7 Quad Core CPU, 16 GB of RAM, NVidia GTX 1050 GPU, SSD ... so it's pretty capable.

If I can provide any more details to help analyzing, I'd be glad to help. Thing is, in this state it can only be used to do some quick things/tests inside the VM but it is not good enough to do anything productive. But for that, the not-enhanced mode is also good enough - so it would be important to have a decent performing UI/UX to really make use of this feature.

As others have noted, VMWare or VirtualBox offers much better performance, but I want to use Hyper-V as I'd have to disable it to use VMWare/VirtualBox, but that means issues with other things where I need Hyper-V (Android Emulators, Docker, ...) - so Hyper-V would be the most convenient and preferred option.

**Comment by Ciantic** [comment]
What does this have to do with HiDPI? I also have 4k screen, but even if I start with low resolution, the performance is poor.

Has anyone managed to configure Ubuntu 18.04 with acceptable video performance?

**Comment by spacecat** [comment]
Bought a new regular low res 25 inch monitor. Ubuntu works fine with enhanced session.

On my hidpi, not so great. Hope to see this fixed in the next summer/ fall windows update.

Also, still looking forward to the ubuntu latest version in the quick create wizard!

**Comment by nickcoad** [comment]
Experiencing the same performance issues. My setup is basically identical to @codekoenig's. The VM really is literally unusable in this state and as others have said, I'd happily use VirtualBox instead but Hyper-V is required for Docker - a common scenario.

**Comment by Ciantic** [comment]
I tried with RemoteFX (by disabling a enhanced mode, since those two does not work together).

I was able to watch YouTube video (albeit the display resolution was low). The best would be for Microsoft to implement some other way for enhanced mode, which does not require xrdp, so we could use RemoteFX instead.

Yard stick for good performance is, that can you watch a video through a Hyper-V? If not, then back to drawing board, the current setup is not good enough.

**Comment by code4clouds** [comment]
Why not just write an Open Source video driver for Linux that is supported by Hyper-V?  Fix it natively...

**Comment by robcresswell** [comment]
@code4clouds "why not just"?? You say that like it's a Friday afternoon task. It's not a trivial thing to do.

**Comment by rich-nahra** [comment]
until the desktop experience leverages hardware acceleration this project is sadly DOA.  I would like nothing more for this project to succeed

**Comment by novaterata** [comment]
I just noticed that after upgrading my VM Configuration Version from 8.2 to 8.3, I started experiencing the same slowness where each frame is drawn painfully slow, so it appears to be some regression. With 8.3 I was able to enable RemoteFX though, and (without using xrdp) it's performance was fine but the resolution was stuck. Hopefully I can get xrdp to work and everything will be fine again.

**Comment by novaterata** [comment]
If you are like me and just want to get back to where you were before the 8.3 upgrade, there is hope! Using Powershell create a new VM with an 8.2 configuration: ` New-VM -Version 8.2 -Name Ubuntu2 -Generation 2` Then set it up to use the hard drive from your previous VM and all the other relevant settings. Now my graphics performance is acceptable.

**Comment by worthwhileindustries** [comment]
I suppose that depends on what you define as "acceptable" This should have feature parity with virtualbox IMHO and it doesn't. I appreciate the work that went into this but, there was a lot of marketing hype around this feature and it is a ways off from quality of which virtualbox delivers. If it weren't for having to use hyper-v with docker I would go back to virtualbox. Aside from performance, I still can't resize dynamically on the fly.

**Comment by Ciantic** [comment]
I think everyone who is stuck with Hyper-V should say something here: https://github.com/docker/for-win/issues/2127

The reason we are stuck with Hyper-V is because of Docker, but if they just added VirtualBox support back we could switch back to that.

**Comment by cwilhit** [comment]
Hey all, I appreciate the feedback we're getting on this thread. This has really helped me get a sense of what the gaps are in the experience offered today through Hyper-V.

The feedback we're getting really stems back to the lack of **vGPU** acceleration. Because we don't offer a vGPU, when you throw a high DPI monitor or display into the mix, it means we have to push all those pixels around entirely on the CPU. For standard res displays, there's less pixels to push and the performance bottleneck is unnoticeable. As soon as you jump up to a high res display (like the one on my surface book)...well, that's a lot of pixels to push and performance starts to degrade.

Of course, we acknowledge that high DPI displays are **commonplace** in most user's setups, so this is a completely valid pain point to experience.

**Comment by codekoenig** [comment]
Hey @cwilhit - thanks for your feedback. I just want to stress again that this is not a problem just on high DPI monitors as myself and multiple others have expressed above. It's _better_ on regular DPI screens but far from unnoticeable. I can utilize 4 cores to nearly 80 % just by moving my mouse pointer around on the Ubuntu Desktop (1080p screen). Besides UI performance, there are also issues with keyboard input lag as was also reported by multiple people in this issue.

Are there any plans for vGPU support in Hyper-V in the future?

**Comment by Fabyao** [comment]
@robcresswell I am sharing my experience in dealing with both HyperV and WSL. For those who do not have the luxury to wait "on this niche issue" to be resolved, my comments might be give them an alternative. Indeed an option. I personally wouldn't mind somebody coming here and say:  _hey! I have this option, it might work for you_. It is a proactive way of dealing with things. In my view this is better than somebody hoping that for the best. Hoping for a "Any rough roadmap" that might or might not come.

**Comment by robcresswell** [comment]
@Fabyao My point is that anyone who has been able to find this report by learning about virtualisation will be well aware of the alternatives, and an issue tracker for a specific bug is not the place for discussing pro's and con's of a particular system. Just general OSS etiquette to allow maintainers to work easily without distractions.

**Comment by Fabyao** [comment]
@robcresswell My point is that I welcome any alternatives and suggestions not just by the maintainers but also by the community. Many users in the thread have done so and I am glad. You are making assumptions about anyone who finds this issue will be well-versed about alternatives. I created this issue and was not aware of how well Ubuntu would fit my requirements. If you think we are distracting the Hyper-V team by having a community driven conversation, I would suggest you create yourself a thread where you can set you own rules and stop people from expressing their alternate views.

**Comment by cwilhit** [comment]
@robcresswell As you'd probably expect with any software team, Hyper-V has finite resources to go around to solve a wide range of interesting virtualization problems. At this time, we do not have an ETA for bringing vGPU support to Linux. 

**Also as a general FYI**: We do have a perf fix rolling out in the latest Windows insider build released today (17738) to address a bug we found. To level-set expectations regarding the fix:  the fix is not promising native performance, but it does bring performance parity to be close to on par with what you'd get via Enhanced mode Windows VMs. If you compare the enhanced mode Linux VM to an ehnanced mode Windows VM (no vGPU), you'll notice similar quality in terms of Youtube video playback stuttering or fishgl framerate test conducted from a browser.

There's no change necessary to your VM to take advantage of this, but your host will need to be the latest insider build.

**Comment by robcresswell** [comment]
@cwilhit Of course, appreciate the candid feedback; helps us evaluate options etc. Thanks for the information about the incoming perfect update too.

@Fabyao Your call. I'm just pointing out that in general, off-topic discussions are discouraged in issue trackers. If you want to do it anyway, go for it. It's not my place to silence you, just attempting to give some advice.

**Comment by mendhak** [comment]
Thanks @cwilhit - to give a bit of context, many enterprises/corporates now implement DeviceGuard and CredentialGuard on Windows 10.  In turn, these features require HyperV, and that in turn means a Type2 hypervisor (VirtualBox) is no longer an option.   

Our teams need a Linux development environment in a VM, and the performance as noted above is sluggish.  For reference - 2 monitors 2560x1440, a variety of CPUs from i7 3rd gen to 7th gen, 32GB RAM, 2 TB SSDs. 

One other option we've found for now is NoMachine Workstation for Linux, however that limits us to a single monitor and its performance is decent but not great.   The HyperV Enhanced Session with these Linux VM Tools would be the most ideal setup.  Of course we do understand your constraints and priorities will not always match up with user expectations. But hope that gives some extra info or a bit of ammunition if ever needed.

**Comment by tzographos** [comment]
@cwilhit  1280x1024 resolution is not considered "hi-res" by today's standards, yet the lack of hardware acceleration in graphics makes the experience horrible (due to software rendering) even on a decent modern CPU (which is expected since CPU's are not optimized for graphics manipulation, even if the resolution in low).

Anyway, the bottom line is: lack of vGPU = frustrating experience; and, as it seems, many people would agree.

**Comment by Zaris001** [comment]
It just might be that helping to run linux on your workstation is not really a priority for MS...

**Comment by tzographos** [comment]
@Zaris001 [but...](https://cloudblogs.microsoft.com/uploads/prod/2018/03/ms_loves_linux.png)

**Comment by Loyen** [comment]
I can confirm @cwilhit that video playback is indeed much better. The UI is still sluggish, but without vGPU that is kind of what to expect from it. At least you are going the right direction, but more frequent updates would definitely be appropriated.

**Comment by rich-nahra** [comment]
An earlier response indicated latest insider build improved performance by
fixing a bug in hyperv. I tried and it seems much better now. I'd say it's
at least useable now but still not on par with windows RDP sessions.

**Comment by bueeler** [comment]
Will this fix bei included also in Windows 10 1803? Or do we need to wait for 1809?

**Comment by cwilhit** [comment]
@bueeler The fix is available in insider builds right now or you can wait and get it with the next release of Windows in the fall.

**Comment by nathanielwarner** [comment]
@cwilhit If implementing vGPU support for Linux guests isn't a priority, could you at least make it possible to change the zoom level for enhanced sessions so as to improve performance on HiDPI screens by reducing presented pixel density? Right now it's grayed out for "enhanced" session.

Actually this would improve Hyper-V usability for Windows guests as well since RemoteFX isn't really powerful enough for HiDPI...

**Comment by SoreGums** [comment]
Insiders preview is not useful for people on LTSB 1607.

Is there a way to run Ubuntu 18.04 at 4k res (3840x2160) full screen as a Hyper-V guest?
Enhanced mode is off the table, does RemoteFX work?

**Comment by petesherick** [comment]
Yeah it's a little sluggish without hardware gpu.  Virtualbox wasn't any better for me though. Ok for terminal work anyway.  Finally got rid of that fugly orange-purp with X-arc plus papirus.
i5-4200u, 1080

**Comment by fdmnio** [comment]
Is there a way to run Ubuntu in Enhanced Mode at a low resolution and then zoom the hyper v windows to full screen on my 4K monitor? 

I am asking because even throwing all my PC resources at the VM (created with the quick create wizard) the interface incredibly laggy with any resolution >= full HD.

**Comment by Brekmister** [comment]
First off, I want to confirm that I am having this issue with quite the build.

**Setup**
AMD Ryzen 1700x 8c16t (3.2ghz I think?)
AMD RX 480 8GB
Samsung 960 Evo M.2 SSD
2 x 8GB DDR4-3200 (16GB)
Triple 1080P monitors

I managed to get this working on Debian with various desktop environments as well and do some testing. Same results.

I configured each VM with 16 v-cores and 4GB of RAM. The video performance is still quite stuttery when I go full screen on all of my monitors. This is despite throwing all of the CPU horsepower I got at it. Having a lighter Desktop Environment such as XFCE and LXDE does help a little but YouTube Videos is still a no possibility.

With that said, I have 2 questions I have that may lead us to a solution:
1. Is there a video driver for Hyper-V vGPU acceleration for Linux? If not can we make one?
2. Does xRDP support hardware acceleration? If so  can we make Hyper-V vGPU play nice with it?

I am going to look more into this and maybe post some results in the next 2 weeks or so. If anyone wants to chip in and give some input, I would greatly appreciate it.

**Comment by Brekmister** [comment]
It could also be that xRDP may not be the best solution for Enhanced Mode UX wise. Is there any chance Enhanced mode can work with the Xserver or Wayland directly instead of going through xRDP? That would probably be the ideal solution but it would take a lot of work.

**Comment by bgshacklett** [comment]
@Brekmister That's definitely an exciting thought. I keep reading articles alluding to Weston having an RDP back-end (e.g.: https://wiki.tizen.org/Weston_RDP_access), but I've never found anything "official". I'm certain I'm glossing over some very important items, but at a high level it seems like if we could get some kind of basic pass-through access to the GPU (perhaps the RemoteFX 3d adapter could help here?) and hardware acceleration written for Weston-RDP we'd be in business.

@cwilhit I sincerely empathize with having too many tasks and not enough time to get to them all. Farming some of this work out to the community by keeping the necessary development tasks in the open source realm may be a way around the bottleneck. Do you have any idea on what would need to be exposed as virtual hardware and the level of effort to do so?

**Comment by cwilhit** [comment]
@Brekmister @bgshacklett first off, love the enthusiasm regarding this feature. 

We've covered this a bit earlier in the thread, but I don't mind reiterating here: Enhanced Mode works by transporting your VM display over RDP. It's much like installing xrdp and remoting over the network to a machine, but instead we bypass going over the network and use an optimized transport that goes over hv_sock (think: conventional IPC sockets, but securely provided by the virtualization platform--in this case, Hyper-V). This way, we avoid going over the network and get a safe, efficient solution. RDP over hv_sock is not the issue, nor is xrdp the bottleneck.

What this also means is the vCPUs of your VM will be used to render/encode all the pixels on your VM display before sending them over the vsock. When you scale this up to what is effectively a 4k display....well, that's a lot of pixels for the CPU to push over vsock. In our enhanced Linux VM case, really any resolution above 1080p starts to really influence what the user perceives to be a lag. The solution, as has been discussed earlier in the thread, is to instead do the render/encode of all these pixels on the GPU, which is well-suited for these sorts of things. In this case, you have a few options (all of which are non-starters today):

1. Passthrough GPU device - give an entire GPU to the VM. You would need pro-grade GPU cards, we do not support this for non-Windows Server hosts in Hyper-V, and a few other reasons. You can read more on our docs [here
](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-for-deploying-devices-using-discrete-device-assignment)
2. vGPU - this is where the VM is given a virtualized GPU device. Think of it as the host knowing how to share the GPU with the VM (I believe VirtualBox has an implementation). There is a non-insignificant amount of work to light up such a feature. It's very apparent from this thread there's group of users for which the experience is sub-optimal without vGPU.
3. RemoteFX - this is a type of vGPU implementation. However, we've deprecated this technology and are moving away from it.

**Comment by worthwhileindustries** [comment]
@cwilhit I feel like this xrdp was supposed to solve a lot of issues it didn't like dynamic scaling on the fly, performance etc... if it doesn't aren't we barking up the wrong tree? Are we looking for a solution in the wrong place? Why doesn't hyper-v without xrdp support this the same as something like VBOX does. Why doesn't the standard connection using hyper-v not work. Isn't the client built into hyper-v the problem here? Why doesn't microsoft have feature parity with VBOX instead of adding all these extra layers?

**Comment by Brekmister** [comment]
@cwilhit Care to explain more about the deprecation of RemoteFX? This is quite some shocking news considering that a bunch of companies I know are relying on that technology.

**Comment by Brekmister** [comment]
Ok, so I did some experimentation and research into xRDP. I am still working on investigating this but, I do I bring some bad, not-too-bad and good news.

### bad news: 

RemoteFX GPU has zero support for Linux guests. Which really sucks because as of right now, there really isn't a good and cheap vGPU option that would otherwise work with Hyper-V. Although, that may change, I honestly have no idea what plans Microsoft has in regards to this.

People who don't have a dedicated GPU assigned to the vm or a vGPU solution from AMD or Nvidia is going to be out of luck for now in regards to this. The best solution I can provide for these people is to get them setup with XFCE which is really light and would be much less taxing on the CPU than just plain Ubuntu but, that is another conversation for another issue.

### not-so-bad news: 

1. I confirmed what we have already discussing in this thread, the poor performance of the Enhanced Session Mode is a result of xrdp using software rendering. I confirmed this by testing it bare metal and running `glxinfo | grep llvmpipe` through the terminal directly on the computer and through xrdp.
2. Probably the most important point here, even with a GPU dedicated to the VM, you are still not going to get Hardware Acceleration on Enhanced Session Mode because of how xserver and xrdp works by default. Which is why we are saying that this integration isn't necessarily complete. However...

### good news: 

We can do something about that.

@worthwhileindustries has brought up an interesting point, xrdp does solve a whole lot of issues apart from just simply being an RDP server. Which is why there are a ton of different ways we can make this work. Since there is so many options and ways we can play with, I am currently doing research and exploration to see what would work best for this purpose. From what I found thus far, there are 2 possible routes we can take here:

1. Ride off the success of other companies and use VNC. xrdp can act as a adapter to VNC and I believe we can make it work for our purposes but, there may be some drawbacks which is what I am exploring now.
2. We can do some fun exploring with xrdp and xserver and see if we can get what we want out of that. We can start emailing the devs over at xrdp to get their assistance on this.

I would also like to point out that since we are taking the approach of using RDP, a potential side effect of getting this issue resolved is that RDP into Linux machines may just become so much easier and less complicated. This is because we are essentially using remote desktop to work on the Linux Machine. So not just users of Hyper-V but Linux System Admins may benefit too. This goes the other way around too, anything xrdp that works can be translated to work for us. This includes any linux distro running in bare-metal or dual-boot configuration.

Lots of options out there. I will throw out a solution when I find a good one. If anyone has input in regards to this I would love to hear it.

**Comment by nathanielwarner** [comment]
The latest version of Hyper-V no longer supports adding RemoteFX adapters, so it's safe to say there's not gonna be Linux support for it. Perhaps you guys could work with Intel to implement [GVT-g](https://01.org/igvt-g) on Hyper-V so that it can measure up to Linux-based hypervisors in graphical performance.

**Comment by boarder2** [comment]
I was hoping that 1809 would be an improvement on an i7 SP2 at native resolution but the Ubuntu desktop definitely doesn't work at a reasonably usable speed even on 1809.  Bummer.

**Comment by petesherick** [comment]
If MS has no interest in getting this done, the least they could do is enable a quick on/off toggle for hyper-v that doesn't require a restart.

**Comment by novaterata** [comment]
@cwilhit I posted earlier that I get usable graphical performance (without Enhanced Mode) if the Configuration Version is 8.2, but 8.3 caused the unusable graphics that are like 1fps if that. I don't need Enhanced Mode, so I assumed this was just the bug you mentioned that should be fixed in 1809, but I just tried upgrading the configuration version to 9.0 and it's still the same <1fps graphics as 8.3.

**Comment by RyanEwen** [comment]
> If MS has no interest in getting this done, the least they could do is enable a quick on/off toggle for hyper-v that doesn't require a restart.

Hyper-V is a level 1 hypervisor. The reason you have to reboot is becuase you're rebooting out of Windows 10 and into a Hyper-V-wrapped Windows 10 with all of your hardware essentially passed-through so that you don't even realize you're running your "host" OS inside Hyper-V. It's nuts, but it's also why Hyper-V offers more performance (except obviously in terms of linux displays) than VMware Workstation or VirtualBox (which are level 2, meaning then run on top of Windows).

**Comment by Macmee** [comment]
I'm on a maxed out SB2 running Ubuntu from the gallery with an xRDP session. The frame loss is quite high. Sad to hear this is a common problem. I think I will go back to VMWare and WSL for now.

**Comment by SeanMikha** [comment]
@cwilhit any updates on a ETA for a fix? The insiders build isn’t working and still having issues. This is a pretty big issue. Should folks running Linux in hyper-v just move to another platform?

**Comment by cwilhit** [comment]
No new development to share on this feature request. My post on this thread from Sept 21st is still the latest. I'd recommend either running your enhanced mode connection at a lower resolution or using another virtualization platform that can meet your needs in the iterim.

**Comment by halcyondude** [comment]
> No new development to share on this feature request. My post on this thread from Sept 21st is still the latest. I'd recommend either running your enhanced mode connection at a lower resolution or using another virtualization platform that can meet your needs in the interim.

@cwilhit thanks for the update, and for keeping the community in the loop!

I'm not sure if this is the right place for actual feedback, or if this is better directed in other venues.  

### re: Surface Book 2 15" (i7)

The combination of flipping to a base windows resolution of 1920x1200, then running "full screen" xrdp does move this from *non-starter* --> *workable*, but I do find myself a tiny bit frustrated that this lovely SB2 doesn't live up to it's potential for all of the dev tasks I want to throw at it at it's native/pretty resolution + other wonderfulness.

That said, I find myself really wanting a vGPU option to make GNOME shine.  In practice I end up:

- reverting to using ubuntu as a headless VM (ssh, mapping drives, etc)
- dropping the resolution (and silently wondering why I'm using a SB2 instead something much cheaper)
- considering maintaining ~pets~images using other distro's or spins, and not (too time consuming)
- Taking a deep breath and go back to using a Macbook Pro

I'm curious if there's any way to share roadmap / thoughts around any of the following options:

- adding additional distros OOTB (e.g. Mint, Fedora Spins, or other things that require less of a GPU)
  - perhaps even better: packaging as .deb + .rpm (with CI for various distros) the mods needed to enable customizing images.  
- actual vGPU support for hyper-v (I know...not likely anytime soon)
- Supporting something like VMW's "Unity Mode"
- a working OOTB / supported X client/server running over hv-sock - I've not tried this, has anyone else?

**Comment by SoreGums** [comment]
I managed to drop latency from VSCode that I was getting going via x11/ssh to local vm by running i3-wm and vnc. it is annoying that I can't resize the window on the fly or start multiple windows simply like I can on windows. However, I now have native access to the files in the Linux world so now that docker works well and everything else works with less "yeah, windows doesn't work great for that".

on my 4k screen, i run it as 3400x1700 window, large enough to fit a lot in the view and small enough to see the other windows. windows 10 host runs at 100%

So arch/hyper-v/i3-wm/tigervnc to run a few gui apps works a treat.
I keep this gist up to date when i figure out new things to make setting up next time easier: https://gist.github.com/SoreGums/28f21f5ad724b4e8658c07f1999f5af1

VSCode might look into speeding up X11 - thread here https://github.com/Microsoft/vscode/issues/5243

**Comment by bitsrules** [comment]
I am having the same issue by setup with **very slow graphics** in the GUI.
Windows Server 2019 (host), Ubuntu 18.04 (vm) running on Dell OptiPlex 7050, i7-7700, 32G memory, 512G SSD.

The graphics works well with Ubuntu VMs on VMware Workstation.
It would be nice the graphics could be accelerated using the Intel GPU I have.

**Comment by randomizedthinking** [comment]
I had the same issue before, and eventually switched back to VirtualBox. The slow GUI is unbearable for any normal users.

**Comment by RyanEwen** [comment]
I switched away as well. Even using Proxmox or ESXi _over the internet_ is a better experience :(

**Comment by bgshacklett** [comment]
> I'd recommend either running your enhanced mode connection at a lower resolution or using another virtualization platform that can meet your needs in the interim.

Using another virtualization system is becoming an impossibility for me. So many virtualization use cases on Windows require Hyper-V that using another solution is just not reasonable anymore if the machine is used for any significant amount of modern development work. For example, I was recently forced to enable Hyper-V to enable the use of Docker on my laptop. Similarly, the new sandbox feature requires Hyper-V as well. The push towards Hyper-V makes perfect sense. It's a fantastic virtualization platform and the level of integration afforded by using it makes it perfect for these use cases, so I really can't complain on that front.

Running at a lower resolution (enough to make a difference) means that either the viewport of the VM is reduced significantly because zoom is not available in this mode: ![image](https://user-images.githubusercontent.com/583359/56850395-fa65b800-68cf-11e9-8dae-4823bb893044.png)

@cwilhit How difficult would it be to enable scaling for enhanced-mode Linux VMs? While not a perfect solution (I'm still holding out for a vGPU some day), it would go a long way towards improving things.

**Comment by novaterata** [comment]
Everyone, please try my suggestion of creating a VM with Configuration
version 8.2 (And without Enhanced mode) before you completely write off
Hyper-V. As long as I stay on version 8.2 the graphical performance is
fine. I'm sure it's not the best, but it's certainly usable with an IDE. As
soon as I upgrade to anything higher it becomes completely unusable. There
was a serious regression starting at 8.3 (probably when they added
"Enhanced" support), and based on the posts on this thread,

**Comment by novaterata** [comment]
I meant to finish with: And based on the posts on this thread, I can tell
people are using > 8.2 with Enhanced mode, which is unusable.

**Comment by halcyondude** [comment]
@cwilhit any update from the MS side, and/or updated guidance re: roadmap or futures?

**Comment by SeanMikha** [comment]
@novaterata I didn't see an option for 8.2, are you suggesting we downgrade the version of windows to get to an earlier state of Hyper-v?

**Comment by novaterata** [comment]
No, if you see my earlier post, you have to create the VM using CLI and
choose 8.2 that way. It's very much worth the trouble.

**Comment by SeanMikha** [comment]
Ok, just tested it out, its better. Thanks for sharing @novaterata . It's still not what it used to be though. Microsoft needs to fix this or at the very least give some kind of a time table guys... (@cwilhit )

**Comment by cwilhit** [comment]
We're investigating the performance difference between 8.2 and newer VM configuration versions. I was able to repro; there's a perceivable difference, for sure. Enhanced mode performance seems the same between the two, but basic mode definitely is not.

**Comment by xelra** [comment]
The system I've always wanted to set up is having two virtual desktops and just swipe right and left to switch between the Windows machine and the Linux machine.

If there were a vGPU for the Linux guest, that dream would finally come true. 

There's actually another solution that might make sense these days, because many computers have two GPUs (dedicated and integrated). There's this project called [Looking Glass](https://github.com/gnif/LookingGlass), which 1:1 streams the framebuffer from one GPU to the other. If something similar could be done here, with a thin client on the Windows host that handles display, sound, mouse and keyboard, I feel like that would be the ultimate high performance solution.
I also think that such a solution is by far not as complicated as a vGPU approach and that a talented programmer could probably do it within a few weeks.

Please Microsoft, hear my plea!

**Comment by SoreGums** [comment]
I switched to VMWare workstation which provides adaquate rendering speeds.
Then I stumbled onto NoMachine, it's a remote access system, works pretty
well. I can't be bothered going back to Hyper-V so anyone having issues and
stalled out on setting up any of the other remote options check out
NoMachine (needs to be installed on the Windows host & Linux guest - the
Windows setup includes everything, so turn off the server parts if you
don't want that)

Then turn off the gui stuff in the guest and away you go. I run the remote
session at 2816x1584 and have it stretch to fill the screen of my 3840x2160
15" Laptop screen. Works perfect.

I'm hoping with the new remote awareness being added to VS Code I won't
need to do this for much longer and will take the time to switch back to
Hyper-V. As Linux cli guest run well enough under Hyper-V.

**Comment by Brac24** [comment]
I am going to give my experience just in case it helps. I was having issues as well with Ubuntu 18.04.2 where using Firefox or something as simple as gedit would make this virtually unusable. Just scrolling down a page in Firefox just kept redrawing super slow.The same with moving the gedit window around. What seemed to help for my situation was when first starting the VM I would get a window to choose the resolution I wanted for the VM and by default it would set to 1366 x 768 but if I instead chose a higher resolution then it would work fine. So for me using the VM with the 1366 x 768 default resolution would make it difficult to use but just increasing the resolution would fix this.

**Comment by Metalsand** [comment]
**Enhanced Session/XRDP Screen Redraw Issues**

I see there is the misconception that screen redraw is a performance issue due to the need for software-based rendering combined with xrdp.  This is incorrect - it is not limited to lack of resources and there are multiple redraw issues in xrdp which are by no means limited to refresh rate.  

It appears as if the problems are with specific program groups, probably having to do with the different types of rendering modules or even just specific functions they use.  It's always specific graphical errors that are consistent within groups, where some properly redraw if you move them around, and others like TextEdit can just be entirely problematic.  I would say that some of the specific issues are more consistent to trigger when it's running at max load, but they can also trigger at minimum load as well.  

As a proof that it's not merely a problem with insufficient resources or high resolution, here's an example of a fresh Ubuntu install with nothing else running where Terminal is working fine but TextEdit being of the worst group.  It's running in 800x600 with 8 logical cores of an i6700k and max of 14GB of RAM (8.3 Hyper-V): https://drive.google.com/open?id=1b_f0DJdwAYvbBDEALi5Doh5bhfNnG5eZ I did this session with a Quick Setup for Ubuntu 18 just to confirm I wasn't doing anything wrong.

I should also note that I encountered these same issues nearly a year ago when I last tried to use Linux with Enhanced Session mode using the Linux VM Tool libraries.  Without XRDP/enhanced session, I don't have any of these intermittent issues, even when I scale down the resources.  I don't really have any other issues - that's the only one I encounter.

**Comment by kjmph** [comment]
I am also bit by the slow performance in Hyper-V, yet upgrading to Ubuntu 19.10 does seem to help with the performance fixes in Gnome. Anyone else try that?

**Comment by xylix** [comment]
Slow performance with no HidPI for me on ubuntu 18.04 with gnome. Planning on configuring i3 for my dev environment though so maybe that'll improve it.

**Comment by charlesritchea** [comment]
@xylix Please try my suggestion here of downgrading the Configuration Version (Use hyper-v cli to create new VM with specific version, then change your settings to match your current VM and use your current hard disk image) https://github.com/microsoft/linux-vm-tools/issues/28#issuecomment-487654677 I'm not sure if it will fix HiDPI, but it made a world of difference for me

**Comment by charlesritchea** [comment]
@cwilhit any update on fixing the configuration issue?

**Comment by xylix** [comment]
I tried the older configuration and can't really notice any difference. I think I'll try virtualbox next.

**Comment by michaelbaranov** [comment]
Ubuntu 19.04, VM Configuration Version 9.0, on latest HP ZBook, no HiDPI and I can see frames rendered

**Comment by charlesritchea** [comment]
I had to use 8.2 I think

**Comment by surenderssm** [comment]
Facing similar issues like lag in typing experience (reduces dev productivity).

**Host machine** 
- Windows 10 , Version 10.0.18363 Build 18363
- System Model	HP Z230 SFF Workstation
- 32 GB Ram

**Hype-V VM**
- Ubuntu 18.05.3 LTS (Created via Hyper-V quick create)
- Assigned RAM : 16 GB

Any plans/suggestion to avoid lags ?

**Comment by gabriellima** [comment]
Facing similar issues using newest available configuration version `9.0` from `Hyper-V Quick Create`. 
Version `8.2` worked better, although still laggy.

**Comment by tanmaster** [comment]
Hi, I am new to Hyper-V. I was forced to use this after needing docker for windows...
I have found that the quick setup option for 18.04 ubuntu to be usable. I can see that the mouse curser on a 144hz screen feels just as smooth as in the host windows; however when anything else is animated in ubuntu (moving windows around, or starting applications) i can clearly see ui lags. 
The lags are by far not as bad as posters before me have descirbed tough. The O.S. is usable imo for coding, the experience is just very poor :-)

I used configuration version 9.0
I tried assigning more vCores (from 4 to 8) but that didnt make a difference.

Also for everyone having no sound: [this fixed it for me](https://c-nergy.be/blog/?p=12469).

**Comment by Cumol** [comment]
Where do I find the Quick Create on Windows Server 2019?

**Comment by cwilhit** [comment]
This repo is being archived, so closing this issue.
